# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'animelistUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 700)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.resultList = QtWidgets.QListWidget(self.centralwidget)
        self.resultList.setGeometry(QtCore.QRect(20, 230, 256, 291))
        self.resultList.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.resultList.setObjectName("resultList")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 20, 221, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.searchButton = QtWidgets.QPushButton(self.centralwidget)
        self.searchButton.setGeometry(QtCore.QRect(250, 20, 51, 21))
        self.searchButton.setObjectName("searchButton")
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.setGeometry(QtCore.QRect(290, 240, 93, 28))
        self.addButton.setObjectName("addButton")
        self.currList = QtWidgets.QListWidget(self.centralwidget)
        self.currList.setGeometry(QtCore.QRect(510, 230, 256, 291))
        self.currList.setObjectName("currList")
        self.resultLabel = QtWidgets.QLabel(self.centralwidget)
        self.resultLabel.setGeometry(QtCore.QRect(20, 200, 55, 16))
        self.resultLabel.setObjectName("resultLabel")
        self.clLabel = QtWidgets.QLabel(self.centralwidget)
        self.clLabel.setGeometry(QtCore.QRect(510, 200, 55, 16))
        self.clLabel.setObjectName("clLabel")
        self.deleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteButton.setGeometry(QtCore.QRect(780, 240, 93, 28))
        self.deleteButton.setObjectName("deleteButton")
        self.exportButton = QtWidgets.QPushButton(self.centralwidget)
        self.exportButton.setGeometry(QtCore.QRect(780, 530, 93, 28))
        self.exportButton.setObjectName("exportButton")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(510, 530, 251, 22))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 900, 26))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Search for anime . . ."))
        self.searchButton.setText(_translate("MainWindow", "Search"))
        self.addButton.setText(_translate("MainWindow", "Add"))
        self.resultLabel.setText(_translate("MainWindow", "Results:"))
        self.clLabel.setText(_translate("MainWindow", "List:"))
        self.deleteButton.setText(_translate("MainWindow", "Delete"))
        self.exportButton.setText(_translate("MainWindow", "Export to text"))
